<a href="https://colab.research.google.com/github/shakshi-k/My_projects/blob/Other-fantastic-projects/knn_model(fake_bills).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

In [2]:
from google.colab import files
uploaded = files.upload()

Saving fake_bills.csv to fake_bills.csv

In [8]:
df = pd.read_csv("fake_bills.csv", delimiter = ';')
df.head()

,is_genuine,diagonal,height_left,height_right,margin_low,margin_up,length
0,True,171.81,104.86,104.95,4.52,2.89,112.83
1,True,171.46,103.36,103.66,3.77,2.99,113.09
2,True,172.69,104.48,103.50,4.40,2.94,113.16
3,True,171.36,103.91,103.94,3.62,3.01,113.51
4,True,171.73,104.28,103.46,4.04,3.48,112.54

In [11]:
df[df['is_genuine'] == False]

,is_genuine,diagonal,height_left,height_right,margin_low,margin_up,length
1000,False,172.28,103.95,103.91,4.78,3.31,111.40
1001,False,171.92,103.86,104.30,4.96,3.13,111.29
1002,False,171.59,104.14,104.38,4.97,3.47,111.22
1003,False,172.02,104.33,104.33,5.19,3.21,111.99
1004,False,172.55,104.25,104.23,5.60,3.13,111.72
...,...,...,...,...,...,...,...
1495,False,171.75,104.38,104.17,4.42,3.09,111.28
1496,False,172.19,104.63,104.44,5.27,3.37,110.97
1497,False,171.80,104.01,104.12,5.51,3.36,111.95
1498,False,172.06,104.28,104.06,5.17,3.46,112.25
1499,False,171.47,104.15,103.82,4.63,3.37,112.07

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   is_genuine    1500 non-null   bool
 1   diagonal      1500 non-null   float64
 2   height_left   1500 non-null   float64
 3   height_right  1500 non-null   float64
 4   margin_low    1463 non-null   float64
 5   margin_up     1500 non-null   float64
 6   length        1500 non-null   float64
dtypes: bool(1), float64(6)
memory usage: 71.9 KB

In [32]:
df['length'].unique()

array([112.83, 113.09, 113.16, 113.51, 112.54, 112.81, 113.08, 112.85,
       113.45, 113.22, 113.24, 113.65, 113.19, 112.98, 112.87, 113.01,
       113.47, 113.12, 113.59, 112.57, 112.68, 113.37, 113.34, 113.46,
       113.76, 113.64, 113.56, 113.55, 113.41, 112.92, 112.93, 113.48,
       113.26, 113.93, 112.79, 112.67, 113.2 , 113.5 , 112.9 , 113.53,
       113.31, 113.05, 113.02, 113.28, 113.44, 113.94, 113.07, 112.4 ,
       113.3 , 113.03, 113.13, 113.39, 113.42, 112.97, 112.82, 114.09,
       112.35, 113.18, 112.95, 113.36, 113.57, 112.74, 113.27, 113.  ,
       113.32, 112.91, 114.04, 112.89, 112.94, 112.59, 113.38, 113.73,
       113.4 , 113.43, 113.71, 113.69, 113.15, 113.6 , 112.6 , 113.17,
       113.33, 113.58, 114.13, 112.78, 113.04, 113.81, 113.52, 113.7 ,
       113.68, 112.47, 112.56, 114.03, 113.35, 113.1 , 113.11, 112.43,
       113.49, 112.88, 113.29, 112.49, 113.14, 113.23, 112.71, 112.96,
       114.08, 113.83, 113.9 , 112.84, 112.99, 113.91, 112.36, 113.06,
       113.66, 113.63, 112.52, 112.64, 112.38, 112.72, 113.87, 112.73,
       112.65, 112.86, 112.76, 113.67, 112.7 , 112.77, 113.25, 112.44,
       113.75, 113.62, 113.74, 112.45, 113.79, 113.77, 113.21, 114.  ,
       112.46, 114.14, 113.54, 113.99, 113.8 , 112.75, 114.07, 113.61,
       113.97, 112.62, 112.34, 112.18, 112.58, 112.61, 113.78, 112.66,
       112.8 , 113.72, 113.84, 113.92, 113.98, 112.69, 111.76, 112.55,
       112.41, 114.44, 112.24, 113.85, 114.15, 113.82, 112.17, 114.32,
       111.4 , 111.29, 111.22, 111.99, 111.72, 110.91, 110.66, 111.25,
       111.71, 111.93, 110.98, 112.07, 111.28, 110.76, 110.99, 110.95,
       111.88, 111.21, 111.57, 111.14, 111.34, 110.83, 111.75, 112.11,
       111.77, 112.02, 111.69, 111.51, 111.48, 111.32, 111.53, 110.5 ,
       111.33, 111.6 , 111.73, 110.73, 111.59, 111.08, 111.79, 111.96,
       111.83, 111.95, 110.35, 111.55, 111.05, 110.94, 111.74, 112.06,
       111.44, 111.56, 110.48, 111.16, 111.42, 111.02, 112.15, 110.36,
       111.87, 111.09, 109.49, 112.5 , 112.13, 111.54, 111.7 , 110.68,
       111.52, 110.78, 111.92, 111.17, 112.09, 111.11, 111.78, 112.03,
       111.43, 111.31, 112.16, 111.61, 110.64, 111.85, 110.97, 111.27,
       112.04, 111.84, 110.8 , 112.39, 110.93, 111.04, 111.49, 112.37,
       111.07, 111.01, 112.33, 110.86, 111.03, 111.46, 111.41, 111.3 ,
       112.2 , 111.45, 111.68, 111.37, 110.69, 110.37, 111.24, 110.7 ,
       111.82, 112.01, 111.91, 112.12, 111.8 , 112.48, 111.2 , 111.06,
       110.87, 110.22, 111.63, 112.08, 111.18, 110.49, 111.35, 110.59,
       112.3 , 111.9 , 111.38, 112.31, 110.29, 112.14, 110.77, 112.32,
       111.5 , 112.1 , 111.67, 110.96, 112.26, 110.34, 111.62, 112.05,
       112.19, 110.61, 112.53, 112.29, 111.94, 112.  , 111.23, 110.74,
       112.23, 110.31, 111.47, 109.97, 110.53, 111.89, 111.58, 111.13,
       110.71, 111.81, 112.28, 111.64, 111.86, 112.42, 110.44, 110.75,
       110.89, 112.51, 110.52, 111.26, 111.36, 109.93, 111.98, 112.25])

In [47]:
df['margin_low'].fillna(df['margin_low'].mean(), inplace = True)

In [48]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [49]:
X = df.drop(columns='is_genuine')
y = df['is_genuine']

In [50]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2,random_state = 42)

In [51]:
model = KNeighborsClassifier()

In [52]:
model.fit(X_train, y_train)

KNeighborsClassifier()

In [53]:
model.fit(X_train, y_train)

KNeighborsClassifier()

In [57]:
y_pred = model.predict(X_test)
accuracy_score(y_test, y_pred)

0.9866666666666667